name: número de Reynolds
markdown: kramdown
permalink: :year/:month/:title
main_image: "images/numerodereynolds_logo.svg"
description: "descrição awesome"
plugins:
 - jekyll-coffeescript

#social
twitter_username: duartedrumond