name: número de Reynolds
markdown: kramdown
permalink: :year/:month/:title
main_image: "https://numerodereynolds.github.io/images/numerodereynolds_logo.png"
main_description: "(mais) um blog pessoal"
plugins:
 - jekyll-coffeescript

#social
twitter_username: duartedrumond