name: número de Reynolds
markdown: kramdown
permalink: :year/:month/:title
main_image: "https://numerodereynolds.github.io/images/numerodereynolds_logo.svg"
main_description: "descrição awesome"
plugins:
 - jekyll-coffeescript

#social
twitter_username: duartedrumond